spring:
  application:
    name: security-oauth2

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_db?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root

  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 3000
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

server:
  port: 8888
