spring:
  application:
    name: security-pwd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_db?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
server:
  port: 8077

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件配配置，配置接口与Mapper文件


